// 生成产物：scripts/gen-catalog.mjs 解析 DSH ui-theme 样式表生成。
// 禁止手改；DSH 升级后重跑 `node scripts/gen-catalog.mjs --dsh <checkout>` 并提交 diff。
export const CATALOG_DSH_VERSION = "0.1.0-rc.5"

export const CATALOG = [
  { name: "--ds-ease-in-out", group: "other", light: "cubic-bezier(0.4, 0, 0.2, 1)", dark: "cubic-bezier(0.4, 0, 0.2, 1)", valueType: "easing", safety: "safe", scope: "local", description: "" },
  { name: "--ds-font-family-code", group: "font", light: "'SF Mono', 'JetBrains Mono', 'Fira Code', Consolas,\n    'Liberation Mono', Menlo, Courier, 'PingFang SC', 'Microsoft YaHei'", dark: "'SF Mono', 'JetBrains Mono', 'Fira Code', Consolas,\n    'Liberation Mono', Menlo, Courier, 'PingFang SC', 'Microsoft YaHei'", valueType: "font-family", safety: "safe", scope: "local", description: "" },
  { name: "--ds-transition-duration", group: "other", light: "0.2s", dark: "0.2s", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--ds-transition-duration-fast", group: "other", light: "0.1s", dark: "0.1s", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--ds-transition-duration-slow", group: "other", light: "0.3s", dark: "0.3s", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsh-scrollbar-thumb", group: "scrollbar", light: "var(--dsw-alias-scrollbar-bg-l1)", dark: "var(--dsw-alias-scrollbar-bg-l1)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsh-scrollbar-thumb-hover", group: "scrollbar", light: "var(--dsw-alias-scrollbar-hover-l1)", dark: "var(--dsw-alias-scrollbar-hover-l1)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsh-scrollbar-width", group: "scrollbar", light: "8px", dark: "8px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-bg-base", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-950)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-layer-1", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-875)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-layer-2", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-layer-3", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-mask-1", group: "alias-bg", light: "rgba(0, 0, 0, 0.24)", dark: "rgba(0, 0, 0, 0.5)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-mask-2", group: "alias-bg", light: "rgba(0, 0, 0, 0.12)", dark: "rgba(0, 0, 0, 0.2)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-mask-3", group: "alias-bg", light: "rgba(0, 0, 0, 0.48)", dark: "rgba(0, 0, 0, 0.48)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-mask-drop", group: "alias-bg", light: "rgba(255, 255, 255, 0.7)", dark: "rgba(39, 39, 48, 0.7)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-mask-photo", group: "alias-bg", light: "rgba(0, 0, 0, 0.88)", dark: "rgba(0, 0, 0, 0.88)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-module-platform", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-60)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-multi-select", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-60)", dark: "var(--dsw-static-neutral-850)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-overlay", group: "alias-bg", light: "var(--dsw-static-neutral-bluish-150)", dark: "var(--dsw-static-neutral-bluish-700)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-bg-skeleton", group: "alias-bg", light: "rgba(0, 0, 0, 0.04)", dark: "rgba(255, 255, 255, 0.08)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-inverted", group: "alias-border", light: "rgba(0, 0, 0, 0)", dark: "rgba(255, 255, 255, 0.06)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-inverted2", group: "alias-border", light: "rgba(0, 0, 0, 0)", dark: "rgba(255, 255, 255, 0.08)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-l1", group: "alias-border", light: "rgba(0, 0, 0, 0.04)", dark: "rgba(255, 255, 255, 0.06)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-l2", group: "alias-border", light: "rgba(0, 0, 0, 0.1)", dark: "rgba(255, 255, 255, 0.12)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-l2-darkmode-thin", group: "alias-border", light: "rgba(0, 0, 0, 0.1)", dark: "rgba(255, 255, 255, 0.06)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-l3", group: "alias-border", light: "rgba(0, 0, 0, 0.12)", dark: "rgba(255, 255, 255, 0.16)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-border-l4", group: "alias-border", light: "rgba(0, 0, 0, 0.16)", dark: "rgba(255, 255, 255, 0.2)", valueType: "color", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-brand-primary", group: "alias-brand", light: "var(--dsw-static-neutral-bluish-1000)", dark: "var(--dsw-static-neutral-bluish-50)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-brand-primary-invert", group: "alias-brand", light: "var(--dsw-static-neutral-bluish-1000)", dark: "var(--dsw-static-neutral-bluish-50)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-brand-primary-new-colorprimary-new-color", group: "alias-brand", light: "rgb(65, 118, 230)", dark: "var(--dsw-static-deepseek-450)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-brand-text", group: "alias-brand", light: "var(--dsw-static-neutral-bluish-1000)", dark: "var(--dsw-static-neutral-bluish-50)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-contrast-fill", group: "alias-button", light: "var(--dsw-static-neutral-bluish-700)", dark: "var(--dsw-static-neutral-bluish-50)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-elevated-fill", group: "alias-button", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-floating-fill", group: "alias-button", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-floating-hover", group: "alias-button", light: "var(--dsw-static-neutral-bluish-75)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-ghost-active-border", group: "alias-border", light: "var(--dsw-static-neutral-bluish-500)", dark: "var(--dsw-static-neutral-bluish-600)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-button-ghost-active-fill", group: "alias-button", light: "var(--dsw-static-neutral-bluish-100)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-ghost-active-hover", group: "alias-button", light: "var(--dsw-static-neutral-bluish-150)", dark: "var(--dsw-static-neutral-bluish-700)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-info-fill", group: "alias-button", light: "var(--dsw-static-deepseek-500)", dark: "var(--dsw-static-deepseek-400)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-info-hover", group: "alias-button", light: "var(--dsw-static-deepseek-400)", dark: "var(--dsw-static-deepseek-500)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-primary-dimmed", group: "alias-button", light: "var(--dsw-static-neutral-bluish-100)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-primary-fill", group: "alias-button", light: "var(--dsw-alias-brand-primary)", dark: "var(--dsw-alias-brand-primary)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-primary-hover", group: "alias-button", light: "var(--dsw-static-neutral-bluish-750)", dark: "var(--dsw-static-neutral-bluish-100)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-tool-bar-fill", group: "alias-button", light: "rgba(84, 85, 87, 0.5)", dark: "rgba(84, 85, 87, 0.5)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-tool-bar-fill-invisible", group: "alias-button", light: "rgba(31, 31, 31, 0.36)", dark: "rgba(31, 31, 31, 0.36)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-button-tool-bar-hover", group: "alias-button", light: "rgba(84, 85, 87, 0.6)", dark: "rgba(84, 85, 87, 0.6)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-interactive-bg-active", group: "alias-interactive", light: "rgba(38, 49, 72, 0.1)", dark: "rgba(255, 255, 255, 0.14)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-interactive-bg-hover", group: "alias-interactive", light: "rgba(38, 49, 72, 0.06)", dark: "rgba(255, 255, 255, 0.08)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-interactive-bg-hover-accent", group: "alias-interactive", light: "rgba(38, 49, 72, 0.14)", dark: "rgba(255, 255, 255, 0.24)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-interactive-bg-hover-danger", group: "alias-interactive", light: "rgba(236, 19, 19, 0.05)", dark: "rgba(242, 90, 90, 0.15)", valueType: "color", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-interactive-bg-hover-solid", group: "alias-interactive", light: "var(--dsw-static-neutral-bluish-75)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-label-caption", group: "alias-label", light: "var(--dsw-static-neutral-bluish-400)", dark: "var(--dsw-static-neutral-bluish-600)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-dimmed", group: "alias-label", light: "var(--dsw-static-neutral-bluish-200)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-primary", group: "alias-label", light: "var(--dsw-static-neutral-bluish-1000)", dark: "var(--dsw-static-neutral-bluish-50)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-primary-bluish", group: "alias-label", light: "var(--dsw-static-blue-900)", dark: "var(--dsw-static-neutral-bluish-50)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-primary-dimmed", group: "alias-label", light: "var(--dsw-static-neutral-bluish-950)", dark: "var(--dsw-static-neutral-bluish-100)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-primary-foreground", group: "alias-label", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-1000)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-primary-inverted", group: "alias-label", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-secondary", group: "alias-label", light: "var(--dsw-static-neutral-bluish-700)", dark: "var(--dsw-static-neutral-bluish-300)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-label-tertiary", group: "alias-label", light: "var(--dsw-static-neutral-bluish-600)", dark: "var(--dsw-static-neutral-bluish-400)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-markdown-citation", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-100)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-code-block", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-50)", dark: "var(--dsw-static-neutral-bluish-900)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-code-block-banner", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-50)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-code-segment-selected", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-code-segment-unselected", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-75)", dark: "var(--dsw-static-neutral-bluish-900)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-inline-code", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-100)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-placeholder", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-60)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-markdown-tag", group: "alias-markdown", light: "var(--dsw-static-neutral-bluish-75)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-scrollbar-bg-l1", group: "alias-scrollbar", light: "var(--dsw-static-neutral-200)", dark: "var(--dsw-static-neutral-700)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-scrollbar-bg-l2", group: "alias-scrollbar", light: "var(--dsw-static-neutral-200)", dark: "var(--dsw-static-neutral-600)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-scrollbar-hover-l1", group: "alias-scrollbar", light: "var(--dsw-static-neutral-300)", dark: "var(--dsw-static-neutral-600)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-scrollbar-hover-l2", group: "alias-scrollbar", light: "var(--dsw-static-neutral-300)", dark: "var(--dsw-static-neutral-550)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-business-primary", group: "alias-state", light: "var(--dsw-static-deepseek-500)", dark: "var(--dsw-static-deepseek-400)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-business-tertiary", group: "alias-state", light: "var(--dsw-static-deepseek-100)", dark: "var(--dsw-static-deepseek-800)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-error-primary", group: "alias-state", light: "var(--dsw-static-red-600)", dark: "var(--dsw-static-red-400)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-error-secondary", group: "alias-state", light: "var(--dsw-static-red-400)", dark: "var(--dsw-static-red-400)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-success-primary", group: "alias-state", light: "var(--dsw-static-green-500)", dark: "var(--dsw-static-green-500)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-success-secondary", group: "alias-state", light: "var(--dsw-static-green-400)", dark: "var(--dsw-static-green-400)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-success-tertiary", group: "alias-state", light: "var(--dsw-static-green-100)", dark: "var(--dsw-static-green-900)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-warn-label", group: "alias-label", light: "var(--dsw-static-amber-600)", dark: "var(--dsw-static-amber-600)", valueType: "string", safety: "safe", scope: "global", description: "" },
  { name: "--dsw-alias-state-warn-primary", group: "alias-state", light: "var(--dsw-static-amber-500)", dark: "var(--dsw-static-amber-500)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-warn-secondary", group: "alias-state", light: "var(--dsw-static-amber-400)", dark: "var(--dsw-static-amber-400)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-state-warn-tertiary", group: "alias-state", light: "var(--dsw-static-amber-100)", dark: "var(--dsw-static-amber-900)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-toast-bg", group: "alias-overlay", light: "var(--dsw-static-neutral-bluish-800)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-alias-tooltip-bg", group: "alias-overlay", light: "var(--dsw-static-neutral-bluish-850)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-16", group: "font", light: "16px/24px var(--dsw-font-family)", dark: "16px/24px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-16-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-16-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-16-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-16-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-16-line-height", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-strong-16", group: "font", light: "500 16px/24px var(--dsw-font-family)", dark: "500 16px/24px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-strong-16-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-strong-16-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-strong-16-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-strong-16-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-base-strong-16-line-height", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-family", group: "font", light: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC',\n    'Hiragino Sans GB', 'Microsoft YaHei', 'Helvetica Neue', Helvetica, Arial, sans-serif", dark: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC',\n    'Hiragino Sans GB', 'Microsoft YaHei', 'Helvetica Neue', Helvetica, Arial, sans-serif", valueType: "font-family", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-l-20", group: "font", light: "500 20px/28px var(--dsw-font-family)", dark: "500 20px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-l-20-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-l-20-font-size", group: "font", light: "20px", dark: "20px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-l-20-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-l-20-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-l-20-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-m-18", group: "font", light: "500 16px/28px var(--dsw-font-family)", dark: "500 16px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-m-18-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-m-18-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-m-18-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-m-18-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-m-18-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base", group: "font", light: "16px/28px var(--dsw-font-family)", dark: "16px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-italic", group: "font", light: "italic 16px/28px var(--dsw-font-family)", dark: "italic 16px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-italic-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-italic-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-italic-font-style", group: "font", light: "italic", dark: "italic", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-italic-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-italic-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong", group: "font", light: "600 16px/28px var(--dsw-font-family)", dark: "600 16px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-font-weight", group: "font", light: "600", dark: "600", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-italic", group: "font", light: "italic 600 16px/28px var(--dsw-font-family)", dark: "italic 600 16px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-italic-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-italic-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-italic-font-style", group: "font", light: "italic", dark: "italic", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-italic-font-weight", group: "font", light: "600", dark: "600", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-italic-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-base-strong-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code", group: "font", light: "14px/22px var(--ds-font-family-code)", dark: "14px/22px var(--ds-font-family-code)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block", group: "font", light: "13px/22px var(--ds-font-family-code)", dark: "13px/22px var(--ds-font-family-code)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-font-family", group: "font", light: "var(--ds-font-family-code)", dark: "var(--ds-font-family-code)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-font-size", group: "font", light: "13px", dark: "13px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-line-height", group: "font", light: "22px", dark: "22px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-small", group: "font", light: "12px/18px var(--ds-font-family-code)", dark: "12px/18px var(--ds-font-family-code)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-small-font-family", group: "font", light: "var(--ds-font-family-code)", dark: "var(--ds-font-family-code)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-small-font-size", group: "font", light: "12px", dark: "12px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-small-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-small-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-block-small-line-height", group: "font", light: "18px", dark: "18px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-font-family", group: "font", light: "var(--ds-font-family-code)", dark: "var(--ds-font-family-code)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-code-line-height", group: "font", light: "22px", dark: "22px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h1", group: "font", light: "700 24px/34px var(--dsw-font-family)", dark: "700 24px/34px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h1-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h1-font-size", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h1-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h1-font-weight", group: "font", light: "700", dark: "700", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h1-line-height", group: "font", light: "34px", dark: "34px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h2", group: "font", light: "700 22px/32px var(--dsw-font-family)", dark: "700 22px/32px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h2-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h2-font-size", group: "font", light: "22px", dark: "22px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h2-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h2-font-weight", group: "font", light: "700", dark: "700", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h2-line-height", group: "font", light: "32px", dark: "32px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h3", group: "font", light: "700 20px/30px var(--dsw-font-family)", dark: "700 20px/30px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h3-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h3-font-size", group: "font", light: "20px", dark: "20px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h3-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h3-font-weight", group: "font", light: "700", dark: "700", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h3-line-height", group: "font", light: "30px", dark: "30px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h4", group: "font", light: "600 16px/28px var(--dsw-font-family)", dark: "600 16px/28px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h4-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h4-font-size", group: "font", light: "16px", dark: "16px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h4-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h4-font-weight", group: "font", light: "600", dark: "600", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-h4-line-height", group: "font", light: "28px", dark: "28px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small", group: "font", light: "14px/24px var(--dsw-font-family)", dark: "14px/24px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-italic", group: "font", light: "italic 14px/24px var(--dsw-font-family)", dark: "italic 14px/24px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-italic-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-italic-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-italic-font-style", group: "font", light: "italic", dark: "italic", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-italic-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-italic-line-height", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-line-height", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong", group: "font", light: "600 14px/24px var(--dsw-font-family)", dark: "600 14px/24px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-font-weight", group: "font", light: "600", dark: "600", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-italic", group: "font", light: "italic 600 14px/24px var(--dsw-font-family)", dark: "italic 600 14px/24px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-italic-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-italic-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-italic-font-style", group: "font", light: "italic", dark: "italic", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-italic-font-weight", group: "font", light: "600", dark: "600", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-italic-line-height", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-small-strong-line-height", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table", group: "font", light: "15px/25px var(--dsw-font-family)", dark: "15px/25px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-font-size", group: "font", light: "15px", dark: "15px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-head", group: "font", light: "500 15px/25px var(--dsw-font-family)", dark: "500 15px/25px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-head-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-head-font-size", group: "font", light: "15px", dark: "15px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-head-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-head-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-head-line-height", group: "font", light: "25px", dark: "25px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-markdown-table-line-height", group: "font", light: "25px", dark: "25px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-14", group: "font", light: "14px/22px var(--dsw-font-family)", dark: "14px/22px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-14-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-14-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-14-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-14-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-14-line-height", group: "font", light: "22px", dark: "22px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-strong-14", group: "font", light: "500 14px/22px var(--dsw-font-family)", dark: "500 14px/22px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-strong-14-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-strong-14-font-size", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-strong-14-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-strong-14-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-s-strong-14-line-height", group: "font", light: "22px", dark: "22px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xl-24", group: "font", light: "600 24px/32px var(--dsw-font-family)", dark: "600 24px/32px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xl-24-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xl-24-font-size", group: "font", light: "24px", dark: "24px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xl-24-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xl-24-font-weight", group: "font", light: "600", dark: "600", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xl-24-line-height", group: "font", light: "32px", dark: "32px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-13", group: "font", light: "13px/20px var(--dsw-font-family)", dark: "13px/20px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-13-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-13-font-size", group: "font", light: "13px", dark: "13px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-13-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-13-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-13-line-height", group: "font", light: "20px", dark: "20px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-strong-13", group: "font", light: "500 13px/20px var(--dsw-font-family)", dark: "500 13px/20px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-strong-13-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-strong-13-font-size", group: "font", light: "13px", dark: "13px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-strong-13-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-strong-13-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xs-strong-13-line-height", group: "font", light: "20px", dark: "20px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-12", group: "font", light: "12px/18px var(--dsw-font-family)", dark: "12px/18px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-12-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-12-font-size", group: "font", light: "12px", dark: "12px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-12-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-12-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-12-line-height", group: "font", light: "18px", dark: "18px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-strong-12", group: "font", light: "500 12px/18px var(--dsw-font-family)", dark: "500 12px/18px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-strong-12-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-strong-12-font-size", group: "font", light: "12px", dark: "12px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-strong-12-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-strong-12-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxs-strong-12-line-height", group: "font", light: "18px", dark: "18px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-11", group: "font", light: "11px/14px var(--dsw-font-family)", dark: "11px/14px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-11-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-11-font-size", group: "font", light: "11px", dark: "11px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-11-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-11-font-weight", group: "font", light: "400", dark: "400", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-11-line-height", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-strong-11", group: "font", light: "500 11px/14px var(--dsw-font-family)", dark: "500 11px/14px var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-strong-11-font-family", group: "font", light: "var(--dsw-font-family)", dark: "var(--dsw-font-family)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-strong-11-font-size", group: "font", light: "11px", dark: "11px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-strong-11-font-style", group: "font", light: "normal", dark: "normal", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-strong-11-font-weight", group: "font", light: "500", dark: "500", valueType: "number", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-font-xxxs-strong-11-line-height", group: "font", light: "14px", dark: "14px", valueType: "length", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-linear-gradient-think", group: "gradient", light: "linear-gradient(180deg, #fff 20.19%, rgba(255, 255, 255, 0) 100%)", dark: "linear-gradient(180deg, #151517 20.19%, rgba(21, 21, 23, 0) 100%)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-linear-think-select", group: "other", light: "linear-gradient(180deg, #f5f6f7 20.19%, rgba(245, 246, 247, 0) 100%)", dark: "linear-gradient(180deg, #232325 20.19%, rgba(35, 35, 37, 0) 100%)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-mask-blur", group: "gradient", light: "blur(2px)", dark: "blur(2px)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-shadow-lv1", group: "shadow", light: "0 2px 4px 0 rgba(0, 0, 0, 0.05)", dark: "0 2px 4px 0 rgba(0, 0, 0, 0.05)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-shadow-lv1-blur", group: "shadow", light: "0 4px 12px 0 rgba(0, 0, 0, 0.02)", dark: "0 4px 12px 0 rgba(0, 0, 0, 0.02)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-shadow-lv2", group: "shadow", light: "0 4px 12px 0 rgba(0, 0, 0, 0.02), 0 2px 8px 0 rgba(0, 0, 0, 0.04)", dark: "0 4px 12px 0 rgba(0, 0, 0, 0.02), 0 2px 8px 0 rgba(0, 0, 0, 0.04)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-shadow-lv3", group: "shadow", light: "0 0 1px 0 rgba(0, 0, 0, 0.2), 0 0 4px 0 rgba(0, 0, 0, 0.02), 0 12px 32px 0 rgba(0, 0, 0, 0.08)", dark: "0 0 1px 0 rgba(0, 0, 0, 0.2), 0 0 4px 0 rgba(0, 0, 0, 0.02), 0 12px 32px 0 rgba(0, 0, 0, 0.08)", valueType: "string", safety: "safe", scope: "local", description: "" },
  { name: "--dsw-specific-bubble", group: "specific", light: "var(--dsw-static-deepseek-50)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-bubble-highlight", group: "specific", light: "var(--dsw-static-deepseek-200)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-input-major", group: "specific", light: "var(--dsw-static-neutral-bluish-00)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-login-input", group: "specific", light: "var(--dsw-static-neutral-bluish-50)", dark: "var(--dsw-static-neutral-bluish-900)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-menu", group: "specific", light: "var(--dsw-alias-bg-layer-3)", dark: "var(--dsw-alias-bg-layer-3)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-selector", group: "specific", light: "var(--dsw-static-neutral-bluish-60)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-sidebar-fill", group: "specific", light: "var(--dsw-static-neutral-bluish-50)", dark: "var(--dsw-static-neutral-bluish-900)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-sidebar-nav-item-active", group: "specific", light: "var(--dsw-static-neutral-bluish-100)", dark: "var(--dsw-static-neutral-bluish-750)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-sidebar-nav-item-active-accent", group: "specific", light: "var(--dsw-static-deepseek-100)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-sidebar-nav-item-hover", group: "specific", light: "var(--dsw-static-neutral-bluish-75)", dark: "var(--dsw-static-neutral-bluish-850)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-specific-tip", group: "specific", light: "var(--dsw-static-neutral-bluish-60)", dark: "var(--dsw-static-neutral-bluish-800)", valueType: "string", safety: "caution", scope: "regional", description: "" },
  { name: "--dsw-static-amber-100", group: "static", light: "rgb(254, 245, 231)", dark: "rgb(254, 245, 231)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-amber-400", group: "static", light: "rgb(247, 173, 49)", dark: "rgb(247, 173, 49)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-amber-500", group: "static", light: "rgb(245, 158, 11)", dark: "rgb(245, 158, 11)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-amber-600", group: "static", light: "rgb(221, 134, 41)", dark: "rgb(221, 134, 41)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-amber-900", group: "static", light: "rgb(39, 36, 31)", dark: "rgb(39, 36, 31)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-100", group: "static", light: "rgb(219, 234, 254)", dark: "rgb(219, 234, 254)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-300", group: "static", light: "rgb(147, 197, 253)", dark: "rgb(147, 197, 253)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-400", group: "static", light: "rgb(96, 165, 250)", dark: "rgb(96, 165, 250)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-450", group: "static", light: "rgb(77, 147, 248)", dark: "rgb(77, 147, 248)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-50", group: "static", light: "rgb(239, 246, 255)", dark: "rgb(239, 246, 255)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-500", group: "static", light: "rgb(59, 130, 246)", dark: "rgb(59, 130, 246)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-50p", group: "static", light: "rgb(234, 243, 255)", dark: "rgb(234, 243, 255)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-600", group: "static", light: "rgb(37, 99, 235)", dark: "rgb(37, 99, 235)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-75", group: "static", light: "rgb(229, 240, 255)", dark: "rgb(229, 240, 255)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-800", group: "static", light: "rgb(30, 64, 175)", dark: "rgb(30, 64, 175)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-900", group: "static", light: "rgb(14, 48, 116)", dark: "rgb(14, 48, 116)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-blue-950", group: "static", light: "rgb(23, 37, 84)", dark: "rgb(23, 37, 84)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-100", group: "static", light: "rgb(228, 237, 253)", dark: "rgb(228, 237, 253)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-200", group: "static", light: "rgb(211, 226, 255)", dark: "rgb(211, 226, 255)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-300", group: "static", light: "rgb(183, 200, 254)", dark: "rgb(183, 200, 254)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-400", group: "static", light: "rgb(103, 158, 254)", dark: "rgb(103, 158, 254)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-450", group: "static", light: "rgb(86, 134, 254)", dark: "rgb(86, 134, 254)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-50", group: "static", light: "rgb(237, 243, 254)", dark: "rgb(237, 243, 254)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-500", group: "static", light: "rgb(65, 118, 230)", dark: "rgb(65, 118, 230)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-600", group: "static", light: "rgb(72, 104, 178)", dark: "rgb(72, 104, 178)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-700-delete", group: "static", light: "rgb(47, 76, 143)", dark: "rgb(47, 76, 143)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-800", group: "static", light: "rgb(52, 65, 91)", dark: "rgb(52, 65, 91)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-deepseek-900", group: "static", light: "rgb(40, 49, 66)", dark: "rgb(40, 49, 66)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-green-100", group: "static", light: "rgb(230, 250, 237)", dark: "rgb(230, 250, 237)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-green-400", group: "static", light: "rgb(78, 209, 126)", dark: "rgb(78, 209, 126)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-green-500", group: "static", light: "rgb(34, 197, 94)", dark: "rgb(34, 197, 94)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-green-900", group: "static", light: "rgb(35, 60, 44)", dark: "rgb(35, 60, 44)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-00", group: "static", light: "rgb(255, 255, 255)", dark: "rgb(255, 255, 255)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-100", group: "static", light: "rgb(245, 245, 245)", dark: "rgb(245, 245, 245)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-1000", group: "static", light: "rgb(0, 0, 0)", dark: "rgb(0, 0, 0)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-150", group: "static", light: "rgb(237, 237, 237)", dark: "rgb(237, 237, 237)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-200", group: "static", light: "rgb(229, 229, 229)", dark: "rgb(229, 229, 229)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-250", group: "static", light: "rgb(220, 220, 220)", dark: "rgb(220, 220, 220)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-300", group: "static", light: "rgb(212, 212, 212)", dark: "rgb(212, 212, 212)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-400", group: "static", light: "rgb(162, 164, 166)", dark: "rgb(162, 164, 166)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-50", group: "static", light: "rgb(250, 250, 250)", dark: "rgb(250, 250, 250)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-500", group: "static", light: "rgb(127, 130, 135)", dark: "rgb(127, 130, 135)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-550", group: "static", light: "rgb(101, 103, 107)", dark: "rgb(101, 103, 107)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-600", group: "static", light: "rgb(84, 85, 87)", dark: "rgb(84, 85, 87)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-700", group: "static", light: "rgb(60, 60, 61)", dark: "rgb(60, 60, 61)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-800", group: "static", light: "rgb(41, 41, 41)", dark: "rgb(41, 41, 41)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-850", group: "static", light: "rgb(33, 33, 35)", dark: "rgb(33, 33, 35)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-900", group: "static", light: "rgb(15, 15, 15)", dark: "rgb(15, 15, 15)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-00", group: "static", light: "rgb(255, 255, 255)", dark: "rgb(255, 255, 255)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-100", group: "static", light: "rgb(235, 238, 242)", dark: "rgb(235, 238, 242)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-1000", group: "static", light: "rgb(15, 17, 21)", dark: "rgb(15, 17, 21)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-150", group: "static", light: "rgb(233, 236, 242)", dark: "rgb(233, 236, 242)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-200", group: "static", light: "rgb(225, 229, 238)", dark: "rgb(225, 229, 238)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-300", group: "static", light: "rgb(207, 211, 214)", dark: "rgb(207, 211, 214)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-400", group: "static", light: "rgb(173, 178, 184)", dark: "rgb(173, 178, 184)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-50", group: "static", light: "rgb(249, 250, 251)", dark: "rgb(249, 250, 251)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-500", group: "static", light: "rgb(151, 157, 166)", dark: "rgb(151, 157, 166)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-60", group: "static", light: "rgb(245, 246, 247)", dark: "rgb(245, 246, 247)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-600", group: "static", light: "rgb(129, 133, 140)", dark: "rgb(129, 133, 140)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-700", group: "static", light: "rgb(97, 102, 107)", dark: "rgb(97, 102, 107)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-75", group: "static", light: "rgb(241, 243, 245)", dark: "rgb(241, 243, 245)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-750", group: "static", light: "rgb(67, 69, 74)", dark: "rgb(67, 69, 74)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-800", group: "static", light: "rgb(53, 54, 56)", dark: "rgb(53, 54, 56)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-850", group: "static", light: "rgb(44, 44, 46)", dark: "rgb(44, 44, 46)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-875", group: "static", light: "rgb(35, 35, 36)", dark: "rgb(35, 35, 36)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-900", group: "static", light: "rgb(27, 27, 28)", dark: "rgb(27, 27, 28)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-neutral-bluish-950", group: "static", light: "rgb(21, 21, 23)", dark: "rgb(21, 21, 23)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-red-100", group: "static", light: "rgb(254, 226, 226)", dark: "rgb(254, 226, 226)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-red-400", group: "static", light: "rgb(242, 90, 90)", dark: "rgb(242, 90, 90)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-red-50", group: "static", light: "rgb(254, 242, 242)", dark: "rgb(254, 242, 242)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-red-500", group: "static", light: "rgb(239, 68, 68)", dark: "rgb(239, 68, 68)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-red-600", group: "static", light: "rgb(236, 19, 19)", dark: "rgb(236, 19, 19)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--dsw-static-red-900", group: "static", light: "rgb(87, 12, 12)", dark: "rgb(87, 12, 12)", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-background", group: "shiki", light: "var(--dsw-alias-markdown-code-block)", dark: "var(--dsw-alias-markdown-code-block)", valueType: "string", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-foreground", group: "shiki", light: "var(--dsw-alias-label-primary)", dark: "var(--dsw-alias-label-primary)", valueType: "string", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-comment", group: "shiki", light: "#868e96", dark: "#adb5bd", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-constant", group: "shiki", light: "#1c7ed6", dark: "#4dabf7", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-function", group: "shiki", light: "#6741d9", dark: "#b197fc", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-keyword", group: "shiki", light: "#d6336c", dark: "#faa2c1", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-link", group: "shiki", light: "#1971c2", dark: "#74c0fc", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-parameter", group: "shiki", light: "#e8590c", dark: "#ffa94d", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-punctuation", group: "shiki", light: "#495057", dark: "#ced4da", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-string", group: "shiki", light: "#2f9e44", dark: "#69db7c", valueType: "color", safety: "caution", scope: "local", description: "" },
  { name: "--shiki-token-string-expression", group: "shiki", light: "#2b8a3e", dark: "#8ce99a", valueType: "color", safety: "caution", scope: "local", description: "" },
]
